add error check on devgit origin

diff --git a/bin/adopt-pull b/bin/adopt-pull
--- a/bin/adopt-pull
+++ b/bin/adopt-pull
@@ -46,17 +46,21 @@ fi
 devgit=$(git remote -v | perl -ane'print "$F[1]" if /\borigin\b/ && /\bfetch\b/')
 export devgit
 
+if [[ -z "$devgit" ]]; then
+    echo "Unable to find origin repo name"
+    exit 11
+fi
+
 echo devgit remote is $devgit
 
 [[ "$devgit" =~ bde-oss-tools ]] && echo "Using bde-tools.git" && ghname=bde-tools.git
 [[ "$devgit" =~ bsl-oss ]]   && echo "using bde.git"       && ghname=bde.git
+export ghname
 
 if [[ -z "$ghname" ]]; then
-    echo "Unable to deduce github repo name from $PWD - exiting..."
+    echo "Unable to deduce github repo name from $devgit - exiting..."
     exit 10
 fi
-
-export ghname
 
 gh=$(git remote -v | grep -F "https://github.com/bloomberg/$ghname" | grep fetch | cut -f 1)
 if [[ -z "$gh" ]]; then
